# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|


  config.vm.box = "tiny_deb386"
  config.ssh.username="as"
  config.ssh.password="1234" 
  config.vm.synced_folder "./data", "/vagrant_data"

  COUNT = 2
    (1..COUNT).each do |machine_id|
    config.vm.define "vm#{machine_id}" do |machine|
      machine.vm.hostname="vm#{machine_id}"
      machine.vm.network "private_network", ip: "192.168.56.#{10+machine_id}"
      machine.vm.network "public_network", ip: "192.168.101.#{10+machine_id}"

      if machine_id == COUNT
        machine.vm.provision :ansible do |ansible|
          ansible.limit = "all"
          ansible.playbook = "../ansible/playbook.yaml"
        end
      end
    end
  end
end