---
- name: Pre install
  hosts: all
  remote_user: admin
  become: true
  tags:
    - "Done"

  tasks:

    - name: Get dependecies
      ansible.builtin.apt:
        package:
          - curl
          - ca-certificates
          - gnupg
          - lsb-release
        state: present
        update_cache: true

    - name: Setup gpgs
      ansible.builtin.apt_key:
        url: '{{ item }}'
        state: present
      loop:
        - 'https://packages.cloud.google.com/apt/doc/apt-key.gpg'
        - 'https://download.docker.com/linux/ubuntu/gpg'

    - name: Setup repo
      ansible.builtin.apt_repository:
        repo: '{{ item }}'
        state: present
      loop:
        - 'deb https://apt.kubernetes.io/ kubernetes-xenial main'
        - 'deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'

    - name: Install k8s and docker
      ansible.builtin.apt:
        package:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - kubelet
          - kubeadm
          - kubectl
          - python3-pip
        state: present
        update_cache: true

    - name: Add user to docker group
      ansible.builtin.user:
        name: admin
        group: docker
        state: present

    - name: Install k8s python module
      ansible.builtin.pip:
        name:
          - kubernetes
        state: present

- name: Configure preflights
  remote_user: admin
  become: true
  hosts: all
  tags:
    - "Done"

  tasks:

    - name: Remove swapfile
      ansible.posix.mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      loop:
        - swap
        - none

    - name: Disable swap
      ansible.builtin.command: swapoff -a
      when: ansible_swaptotal_mb > 0
      register: my_output
      changed_when: my_output.rc == 0

    - name: Remove toml
      ansible.builtin.file:
        path: '/etc/containerd/config.toml'
        state: absent
      notify: Restart containerd

  handlers:
    - name: Restart containerd
      ansible.builtin.systemd:
        service: containerd.service
        state: restarted

- name: Configure control plate
  remote_user: admin
  become: false
  hosts: 'k8s-cp'
  tags:
    - "Undone"

  tasks:

    - name: Create .kube
      ansible.builtin.file:
        path: '/home/admin/.kube'
        state: directory
        owner: admin
        group: admin
        mode: '765'

    - name: Copy config
      become: true
      ansible.builtin.copy:
        remote_src: true
        src: '/etc/kubernetes/admin.conf'
        dest: '/home/admin/.kube/config'
        owner: admin
        group: admin
        mode: '765'
      notify: Restart kubelet

    - name: Get CNI
      ansible.builtin.get_url:
        url: 'https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml'
        dest: '~/weave-daemonset-k8s.yaml'
        mode: '644'

    - name: Install CNI
      kubernetes.core.k8s:
        state: present
        src: '~/weave-daemonset-k8s.yaml'

  handlers:
    - name: Restart kubelet
      ansible.builtin.systemd:
        service: kubelet.service
        state: restarted
        enabled: true
